name: push
description: Build and test on push


on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - docs
      - .readthedocs.yaml
      - .gitignore

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
  build:
    name: Build the package for different python versions and operation systems
    uses: ./.github/workflows/build.yml
